services:
  dev-db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest
    networks:
      - test
    volumes:
      - testVolumes:/var/lib/postgresql/data
networks:
  test:
volumes:
  testVolumes: